use imgui::Key;
use sdl2_sys::SDL_Scancode::{
    self, SDL_SCANCODE_0, SDL_SCANCODE_1, SDL_SCANCODE_2, SDL_SCANCODE_3, SDL_SCANCODE_4,
    SDL_SCANCODE_5, SDL_SCANCODE_6, SDL_SCANCODE_7, SDL_SCANCODE_8, SDL_SCANCODE_9, SDL_SCANCODE_A,
    SDL_SCANCODE_APOSTROPHE, SDL_SCANCODE_B, SDL_SCANCODE_BACKSLASH, SDL_SCANCODE_BACKSPACE,
    SDL_SCANCODE_C, SDL_SCANCODE_CAPSLOCK, SDL_SCANCODE_COMMA, SDL_SCANCODE_D, SDL_SCANCODE_DELETE,
    SDL_SCANCODE_DOWN, SDL_SCANCODE_E, SDL_SCANCODE_END, SDL_SCANCODE_EQUALS, SDL_SCANCODE_ESCAPE,
    SDL_SCANCODE_F, SDL_SCANCODE_F1, SDL_SCANCODE_F10, SDL_SCANCODE_F11, SDL_SCANCODE_F12,
    SDL_SCANCODE_F2, SDL_SCANCODE_F3, SDL_SCANCODE_F4, SDL_SCANCODE_F5, SDL_SCANCODE_F6,
    SDL_SCANCODE_F7, SDL_SCANCODE_F8, SDL_SCANCODE_F9, SDL_SCANCODE_G, SDL_SCANCODE_GRAVE,
    SDL_SCANCODE_H, SDL_SCANCODE_HOME, SDL_SCANCODE_I, SDL_SCANCODE_INSERT, SDL_SCANCODE_J,
    SDL_SCANCODE_K, SDL_SCANCODE_KP_0, SDL_SCANCODE_KP_1, SDL_SCANCODE_KP_2, SDL_SCANCODE_KP_3,
    SDL_SCANCODE_KP_4, SDL_SCANCODE_KP_5, SDL_SCANCODE_KP_6, SDL_SCANCODE_KP_7, SDL_SCANCODE_KP_8,
    SDL_SCANCODE_KP_9, SDL_SCANCODE_KP_DIVIDE, SDL_SCANCODE_KP_ENTER, SDL_SCANCODE_KP_EQUALS,
    SDL_SCANCODE_KP_MINUS, SDL_SCANCODE_KP_MULTIPLY, SDL_SCANCODE_KP_PERIOD, SDL_SCANCODE_KP_PLUS,
    SDL_SCANCODE_L, SDL_SCANCODE_LALT, SDL_SCANCODE_LCTRL, SDL_SCANCODE_LEFT,
    SDL_SCANCODE_LEFTBRACKET, SDL_SCANCODE_LGUI, SDL_SCANCODE_LSHIFT, SDL_SCANCODE_M,
    SDL_SCANCODE_MENU, SDL_SCANCODE_MINUS, SDL_SCANCODE_N, SDL_SCANCODE_NUMLOCKCLEAR,
    SDL_SCANCODE_O, SDL_SCANCODE_P, SDL_SCANCODE_PAGEDOWN, SDL_SCANCODE_PAGEUP, SDL_SCANCODE_PAUSE,
    SDL_SCANCODE_PERIOD, SDL_SCANCODE_PRINTSCREEN, SDL_SCANCODE_Q, SDL_SCANCODE_R,
    SDL_SCANCODE_RALT, SDL_SCANCODE_RCTRL, SDL_SCANCODE_RETURN, SDL_SCANCODE_RGUI,
    SDL_SCANCODE_RIGHT, SDL_SCANCODE_RIGHTBRACKET, SDL_SCANCODE_RSHIFT, SDL_SCANCODE_S,
    SDL_SCANCODE_SCROLLLOCK, SDL_SCANCODE_SEMICOLON, SDL_SCANCODE_SLASH, SDL_SCANCODE_SPACE,
    SDL_SCANCODE_T, SDL_SCANCODE_TAB, SDL_SCANCODE_U, SDL_SCANCODE_UP, SDL_SCANCODE_V,
    SDL_SCANCODE_W, SDL_SCANCODE_X, SDL_SCANCODE_Y, SDL_SCANCODE_Z,
};

#[allow(clippy::too_many_lines)]
pub fn sdl_scancode_to_imgui_key(scancode: SDL_Scancode) -> Option<Key> {
    match scancode {
        SDL_SCANCODE_TAB => Some(Key::Tab),
        SDL_SCANCODE_LEFT => Some(Key::LeftArrow),
        SDL_SCANCODE_RIGHT => Some(Key::RightArrow),
        SDL_SCANCODE_UP => Some(Key::UpArrow),
        SDL_SCANCODE_DOWN => Some(Key::DownArrow),
        SDL_SCANCODE_PAGEUP => Some(Key::PageUp),
        SDL_SCANCODE_PAGEDOWN => Some(Key::PageDown),
        SDL_SCANCODE_HOME => Some(Key::Home),
        SDL_SCANCODE_END => Some(Key::End),
        SDL_SCANCODE_INSERT => Some(Key::Insert),
        SDL_SCANCODE_DELETE => Some(Key::Delete),
        SDL_SCANCODE_BACKSPACE => Some(Key::Backspace),
        SDL_SCANCODE_SPACE => Some(Key::Space),
        SDL_SCANCODE_RETURN => Some(Key::Enter),
        SDL_SCANCODE_ESCAPE => Some(Key::Escape),
        SDL_SCANCODE_A => Some(Key::A),
        SDL_SCANCODE_C => Some(Key::C),
        SDL_SCANCODE_V => Some(Key::V),
        SDL_SCANCODE_X => Some(Key::X),
        SDL_SCANCODE_Y => Some(Key::Y),
        SDL_SCANCODE_Z => Some(Key::Z),
        SDL_SCANCODE_B => Some(Key::B),
        SDL_SCANCODE_D => Some(Key::D),
        SDL_SCANCODE_E => Some(Key::E),
        SDL_SCANCODE_F => Some(Key::F),
        SDL_SCANCODE_G => Some(Key::G),
        SDL_SCANCODE_H => Some(Key::H),
        SDL_SCANCODE_I => Some(Key::I),
        SDL_SCANCODE_J => Some(Key::J),
        SDL_SCANCODE_K => Some(Key::K),
        SDL_SCANCODE_L => Some(Key::L),
        SDL_SCANCODE_M => Some(Key::M),
        SDL_SCANCODE_N => Some(Key::N),
        SDL_SCANCODE_O => Some(Key::O),
        SDL_SCANCODE_P => Some(Key::P),
        SDL_SCANCODE_Q => Some(Key::Q),
        SDL_SCANCODE_R => Some(Key::R),
        SDL_SCANCODE_S => Some(Key::S),
        SDL_SCANCODE_T => Some(Key::T),
        SDL_SCANCODE_U => Some(Key::U),
        SDL_SCANCODE_W => Some(Key::W),
        SDL_SCANCODE_1 => Some(Key::Alpha1),
        SDL_SCANCODE_2 => Some(Key::Alpha2),
        SDL_SCANCODE_3 => Some(Key::Alpha3),
        SDL_SCANCODE_4 => Some(Key::Alpha4),
        SDL_SCANCODE_5 => Some(Key::Alpha5),
        SDL_SCANCODE_6 => Some(Key::Alpha6),
        SDL_SCANCODE_7 => Some(Key::Alpha7),
        SDL_SCANCODE_8 => Some(Key::Alpha8),
        SDL_SCANCODE_9 => Some(Key::Alpha9),
        SDL_SCANCODE_0 => Some(Key::Alpha0),
        SDL_SCANCODE_MINUS => Some(Key::Minus),
        SDL_SCANCODE_EQUALS => Some(Key::Equal),
        SDL_SCANCODE_LEFTBRACKET => Some(Key::LeftBracket),
        SDL_SCANCODE_RIGHTBRACKET => Some(Key::RightBracket),
        SDL_SCANCODE_BACKSLASH => Some(Key::Backslash),
        SDL_SCANCODE_SEMICOLON => Some(Key::Semicolon),
        SDL_SCANCODE_APOSTROPHE => Some(Key::Apostrophe),
        SDL_SCANCODE_GRAVE => Some(Key::GraveAccent),
        SDL_SCANCODE_COMMA => Some(Key::Comma),
        SDL_SCANCODE_PERIOD => Some(Key::Period),
        SDL_SCANCODE_SLASH => Some(Key::Slash),
        SDL_SCANCODE_CAPSLOCK => Some(Key::CapsLock),
        SDL_SCANCODE_F1 => Some(Key::F1),
        SDL_SCANCODE_F2 => Some(Key::F2),
        SDL_SCANCODE_F3 => Some(Key::F3),
        SDL_SCANCODE_F4 => Some(Key::F4),
        SDL_SCANCODE_F5 => Some(Key::F5),
        SDL_SCANCODE_F6 => Some(Key::F6),
        SDL_SCANCODE_F7 => Some(Key::F7),
        SDL_SCANCODE_F8 => Some(Key::F8),
        SDL_SCANCODE_F9 => Some(Key::F9),
        SDL_SCANCODE_F10 => Some(Key::F10),
        SDL_SCANCODE_F11 => Some(Key::F11),
        SDL_SCANCODE_F12 => Some(Key::F12),
        SDL_SCANCODE_PRINTSCREEN => Some(Key::PrintScreen),
        SDL_SCANCODE_SCROLLLOCK => Some(Key::ScrollLock),
        SDL_SCANCODE_PAUSE => Some(Key::Pause),
        SDL_SCANCODE_NUMLOCKCLEAR => Some(Key::NumLock),
        SDL_SCANCODE_KP_DIVIDE => Some(Key::KeypadDivide),
        SDL_SCANCODE_KP_MULTIPLY => Some(Key::KeypadMultiply),
        SDL_SCANCODE_KP_MINUS => Some(Key::KeypadSubtract),
        SDL_SCANCODE_KP_PLUS => Some(Key::KeypadAdd),
        SDL_SCANCODE_KP_ENTER => Some(Key::KeypadEnter),
        SDL_SCANCODE_KP_1 => Some(Key::Keypad1),
        SDL_SCANCODE_KP_2 => Some(Key::Keypad2),
        SDL_SCANCODE_KP_3 => Some(Key::Keypad3),
        SDL_SCANCODE_KP_4 => Some(Key::Keypad4),
        SDL_SCANCODE_KP_5 => Some(Key::Keypad5),
        SDL_SCANCODE_KP_6 => Some(Key::Keypad6),
        SDL_SCANCODE_KP_7 => Some(Key::Keypad7),
        SDL_SCANCODE_KP_8 => Some(Key::Keypad8),
        SDL_SCANCODE_KP_9 => Some(Key::Keypad9),
        SDL_SCANCODE_KP_0 => Some(Key::Keypad0),
        SDL_SCANCODE_KP_PERIOD => Some(Key::KeypadDecimal),
        SDL_SCANCODE_KP_EQUALS => Some(Key::KeypadEqual),
        SDL_SCANCODE_MENU => Some(Key::Menu),
        SDL_SCANCODE_LCTRL => Some(Key::LeftCtrl),
        SDL_SCANCODE_LSHIFT => Some(Key::LeftShift),
        SDL_SCANCODE_LALT => Some(Key::LeftAlt),
        SDL_SCANCODE_LGUI => Some(Key::LeftSuper),
        SDL_SCANCODE_RCTRL => Some(Key::RightCtrl),
        SDL_SCANCODE_RSHIFT => Some(Key::RightShift),
        SDL_SCANCODE_RALT => Some(Key::RightAlt),
        SDL_SCANCODE_RGUI => Some(Key::RightSuper),
        _ => None,
    }
}
